name: fpl_api
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - blas=1.0
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - click=7.1.1
  - flask=1.1.1
  - intel-openmp=2020.0
  - itsdangerous=1.1.0
  - jinja2=2.11.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libstdcxx-ng=9.1.0
  - markupsafe=1.1.1
  - mkl=2020.0
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pip=20.0.2
  - python=3.7.7
  - python-dateutil=2.8.1
  - pytz=2019.3
  - readline=8.0
  - setuptools=46.1.3
  - six=1.14.0
  - sqlalchemy=1.3.15
  - sqlite=3.31.1
  - tk=8.6.8
  - werkzeug=1.0.1
  - wheel=0.34.2
  - xz=5.2.4
  - zlib=1.2.11

