# Taken directly from https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
# to use as a template
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.6"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Ensure fpltools is visible
  - export PYTHONPATH="$PYTHONPATH":`pwd`

  # Each subdirectory is separate service (etc.) and each has separate environment - create here
  # - conda env create -q --name test-tools --file=fpltools/environment.yml
  - conda env create -q --name test-etl --file=etl/environment.yml
  # - conda env create -q --name test-api --file=api/environment.yml
  # - conda env create -q --name test-modelling --file=modelling/environment.yml 
  # - conda env create -q --name test-awslambda --file=aws_lambda/environment.yml

script:
  # - conda activate test-tools
  # - python -m pytest fpltools/tests*
  - conda activate test-etl
  - python -m pytest etl/tests* 
  # - conda activate test-api
  # - python -m pytest api/tests*
  # - conda activate test-modelling
  # - python -m pytest modelling/tests*
  # - conda activate test-awslambda
  # - python -m pytest aws_lambda/tests*